- hosts: emu
  gather_facts: no
  vars:
    app_path: /app
  tasks:
    - name: Prepare Deployment Vars
      set_fact:
        new_release_path: "{{ app_path }}/releases/{{ lookup('pipe', 'git describe') }}-{{ lookup('pipe', 'date -u +%Y.%m.%dT%H:%M:%S') }}"
        current_path: "{{ app_path }}/current"

    - name: Create Directory For New Release
      file:
        dest={{ new_release_path }}
        mode=0755
        recurse=yes
        state=directory

    - name: Synchronize Release Directory
      synchronize:
        src: ../dist
        dest: "{{ new_release_path }}"

    - name: Update Current Symlink On New Release Directory
      file:
        src={{ new_release_path }}
        dest={{ current_path }}
        state=link

    - name: Restart Service
      systemd:
        name: emu
        state: restarted
